//
// Generated file, do not edit! Created by nedtool 5.0 from inet/flightcontroller/MobilityControlMessage.msg.
//

#ifndef __INET_MOBILITYCONTROLMESSAGE_M_H
#define __INET_MOBILITYCONTROLMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


namespace inet {

/**
 * Enum generated from <tt>inet/flightcontroller/MobilityControlMessage.msg:19</tt> by nedtool.
 * <pre>
 * enum MsgType
 * {
 * 
 *     CONTROL = 0;
 *     PAR_CHANGE = 1;
 * }
 * </pre>
 */
enum MsgType {
    CONTROL = 0,
    PAR_CHANGE = 1
};

/**
 * Class generated from <tt>inet/flightcontroller/MobilityControlMessage.msg:24</tt> by nedtool.
 * <pre>
 * message MobilityControlMessage
 * {
 *     int msgType @enum(MsgType);
 * }
 * </pre>
 */
class MobilityControlMessage : public ::omnetpp::cMessage
{
  protected:
    int msgType;

  private:
    void copy(const MobilityControlMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MobilityControlMessage&);

  public:
    MobilityControlMessage(const char *name=nullptr, int kind=0);
    MobilityControlMessage(const MobilityControlMessage& other);
    virtual ~MobilityControlMessage();
    MobilityControlMessage& operator=(const MobilityControlMessage& other);
    virtual MobilityControlMessage *dup() const {return new MobilityControlMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getMsgType() const;
    virtual void setMsgType(int msgType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MobilityControlMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MobilityControlMessage& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_MOBILITYCONTROLMESSAGE_M_H

